# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ABInBev Devices' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ABInBev Devices
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'M13Checkbox', :git => 'https://github.com/djbe/M13Checkbox.git', :branch => 'swift_4_2'
  
end
